env:
  ACTIONS_STEP_DEBUG: true
name: Continuous Testing
run-name: Started by ${{github.actor}}
on: [push]
jobs:
    run-test-suite:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11']
                with-orjson: [True, False]
        steps:
            - name: Checkout Main
              uses: actions/checkout@main
            
            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install requirements
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Installing ORJSON
              if: ${{matrix.with-orjson}}
              run: pip install orjson
            
            - name: Run tests
              run: python -m test.test_suite

    run-coverage:
        needs: run-test-suite
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@main
            
            - name: Setup Python
              uses: actions/setup-python@v3
  
            - name: Install requirements
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install coverage
                pip install orjson
            
            - name: Run coverage
              run: |
                coverage run -m test.test_suite
                coverage report

            # Update the coverage badges
            - name: Update coverage badge
              run: |
                COVERAGE=$(coverage report --show-missing | awk 'END{print $NF}')
                echo "COVERAGE: $COVERAGE"  # Debug statement
                sed -i "s|!\[Coverage\](.*.svg)|![Coverage](https://img.shields.io/badge/Coverage-${COVERAGE//\%25}25-brightgreen)|g" README.md
                git add README.md
                git config --local user.name "Hnsson"
                git config --local user.email "emhs21@student.bth.se"
                git commit -m "Update coverage badge [skip ci]" --allow-empty
                git remote set-url origin https://github.com/Hnsson/information-diffusion-boundaries-in-code-review.git
                git push origin main
